### ISSUE TITLE
Add npm-scripts build options automatically

### ISSUE THREAD

**Issue by pavel-savinov** [bryceosterhaus/liferay-npm-tools#5]
Now we have to specify "liferay-npm-scripts build" options in the package.json manually, like "--soy" when we have *.soy files to compile, "--bridge" when we have JS components to export, etc.

It would be great to have only "liferay-npm-scripts build" script in the package.json file, build script can analyse the project and add specific capabilities automatically when necessary.

**Comment by bryceosterhaus** [comment]
Hmm, that would definitely be interesting. I have two initial concerns with that approach:

1. I want to avoid too much "magic" internally so that developers can actually see what it does at face value, rather than having to dig into the source code of the tool. When we used `metal-cli` it became an issue because users weren't able to customize the build process and it did too much magic under the hood.(@jbalsas correct me if i am wrong on that... 😄)
2. Performance impact on build times. This probably wouldn't be a huge deal, but the more logic we add here, the more it might impact build times.

I still think its something good to look in to though. I will investigate and see what can be done and see if we can avoid doing too much magic under the hood.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, I think https://github.com/bryceosterhaus/liferay-npm-tools/issues/6#issuecomment-459646691 applies here as well.

It is true that `metal-cli` was complicated to customize. However, I wouldn't attribute that to it doing "too much magic". For example, having too many custom tools doing specific things different than industry "standards" was one of the biggest hurdles imho.

Defaults have to be properly selected and configuration points carefully crafted to allow for customization and extensibility. I think we can achieve good conventions that "just work" and still offer good customization options for those needing to do more than we can anticipate.

**Comment by bryceosterhaus** [comment]
Good point, I'll work on finding a good middle ground that provides both "it just works" and more advanced configurations.
