### ISSUE TITLE
Increase list of default build dependencies

### ISSUE THREAD

**Issue by jbalsas** [bryceosterhaus/liferay-npm-tools#6]
Currently, when using the `--bundler` option, we bring in different "import" dependencies through the [liferay-npm-bundler-preset-liferay-dev](https://github.com/bryceosterhaus/liferay-npm-tools/blob/master/packages/liferay-npm-bundler-preset-liferay-dev/config.json).

Particularly important are:
- [metal dependencies](https://github.com/bryceosterhaus/liferay-npm-tools/blob/master/packages/liferay-npm-bundler-preset-liferay-dev/config.json#L24-L56)
- [clay dependencies](https://github.com/bryceosterhaus/liferay-npm-tools/blob/master/packages/liferay-npm-bundler-preset-liferay-dev/config.json#L87-L116)

If I understand it correctly, the build script currently [defaults to empty dependencies](https://github.com/bryceosterhaus/liferay-npm-tools/blob/master/packages/liferay-npm-scripts/src/config/liferay-npm-scripts.json#L3).

It would be great to at least default to those we know should be present to avoid having to repeat them several times. This should help us avoid things like:

`journal-web/package.json` 
```json
"dependencies": {
	"clay-dropdown": "^2.5.0",
	"clay-label": "^2.5.0",
	"metal": "^2.5.18",
	"metal-dom": "^2.5.18",
	"metal-soy": "^2.4.5",
	"metal-state": "^2.6.4"
}
```

`journal-web/.liferaynpmscriptsrc`
```json
{
	"build": {
		"dependencies": [
			"clay-radio",
			"clay-link",
			"clay-portal",
			"clay-checkbox",
			"clay-icon",
			"clay-button",
			"clay-icon",
			"clay-dropdown",
			"clay-label",
			...
		]
	}
}
```

See also the mismatch between the `package.json` declared dependencies and the necessary build dependencies, caused by the transitive nature of most of them. This is usually quite tricky and confusing to set up. We could either be very specific, or more lenient with a `clay-*` or `metal-*` glob...

**Comment by bryceosterhaus** [comment]
I looked into this briefly and I think it can be done. A few solutions I came up with, and also a few issues i noticed.

1. Default the dependency config to `["clay-*", "metal-*"]`.
2. Read the dependencies from the package.json and add those modules to the soy dependencies, or we filter those dependencies with clay- and metal- globs.

Both of these solutions seem to work, however I am a bit hesitant to add them. For one, I don't really like the idea of only needing to add non clay and metal to the dependency list, mostly because it'd not very intuitive. I would prefer that the scripts are fairly explicit and don't require a ton of inner knowledge of the source in order for users to be able to use it. Once it starts to become a black box, itll be much harder for people to use.

Secondly, when we start to use globs or blindly add the package.json dependencies to the `--soyDeps` option, it requires the tool to look through a lot more files and this can cause performance issues. For example, I was running both of the options in `frontend-taglib-clay` and it caused the build step to go from 6 seconds to 8 seconds. Granted that isn't a huge leap, but when we `ant all`, that would be across a bunch of modules and add a minute or two to total build time.

I do agree that its annoying to have to redundantly add to both lists though, so I'll keep looking into it in case I am able to find a better solution.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, thanks for looking into this!

Regarding the solution... could `globs` take a bit longer to resolve than if we just listed the exact dependencies, so rather than just doing `clay-*` we can upfront list all the ones we know are available?

Unfortunately for soy, reading from the dependencies isn't enough since `--soyDeps` doesn't handle transitive dependencies. We'd need to traverse every `soyDep` tree to see if in turn it contains other potential `soyDeps` so we could create the final set.

> Both of these solutions seem to work, however I am a bit hesitant to add them. For one, I don't really like the idea of only needing to add non clay and metal to the dependency list, mostly because it'd not very intuitive. I would prefer that the scripts are fairly explicit and don't require a ton of inner knowledge of the source in order for users to be able to use it. Once it starts to become a black box, it'll be much harder for people to use.

While I agree with this, past experience has taught us this is very tricky. After all, people want black boxes, things that `simply work`. The trick is to be flexible enough to allow for those advanced users savy enough to tinker with the default settings and options to achieve a more fine-grained setup. Just look at how [Parcel](https://parceljs.org/) jumped to the spotlight and how quickly Webpack reacted to catch up:

> Parcel Blazing fast, zero configuration web application bundler

>Since version 4.0.0, webpack does not require a configuration file to bundle your project, nevertheless it is incredibly configurable to better fit your needs.

We have a clear target here in Liferay Portal developers. If we're providing libraries to use (Clay, Metal, React), then developers expect the setup for those to be minimal. At least for the very basic things, on the long run, I think convention always end up taking over configuration.

To address your black-box concern, I think we could do a better job at explaining what's happening under the hood in proper docs so people can better understand what to expect and have a clear place to look for information.

**Comment by bryceosterhaus** [comment]
> Regarding the solution... could globs take a bit longer to resolve than if we just listed the exact dependencies, so rather than just doing clay-* we can upfront list all the ones we know are available?

Yeah this might help, I will check it out. Are you thinking of just duplicating the list from liferay-npm-bundler-preset-liferay-dev? I wasn't even entirely sure what those were listed for in that preset, so I will try to wrap my head around that a bit more.

> While I agree with this, past experience has taught us this is very tricky. After all, people want black boxes, things that simply work. The trick is to be flexible enough to allow for those advanced users savy enough to tinker with the default settings and options to achieve a more fine-grained setup.

Ahh this makes a lot of sense and is a good way to think about the line between to much magic but also giving developers flexibility to use the tools they want. I'll take this line of thinking and apply it to both this and issue #5
